system/urls.py
from django.contrib import admin
from django.urls import path
from clubs import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('sign_up/', views.sign_up, name="sign_up"),
    path('log_in/', views.LogInView.as_view(), name="log_in"),
    path('dashboard/', views.ClubListView.as_view(), name="dashboard"),
    path('applications/', views.ApplicationListView.as_view(), name="applications"),
    path('log_out/', views.log_out, name='log_out'),
    path('application/', views.NewApplicationView.as_view(), name="application"),
    path('application/<int:club_id>', views.NewApplicationView.as_view(), name="application"),
    path('close_account/', views.CloseAccountView.as_view(), name="close_account"),
    path('password/', views.password, name='password'),
    path('profile/', views.profile, name='profile'),
    path('applications/cancel_application/<int:application_id>', views.CancelApplicationView.as_view(), name='cancel_application'),
    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('create_club/', views.CreateClubView.as_view(), name="create_club"),
    path('club/<int:club_id>', views.ClubHomeView.as_view(), name="club_home"),
    path('club/<int:club_id>/members/', views.MembersListView.as_view(), name='members_list'),
    path('club/<int:club_id>/applications/', views.ClubApplicationsView.as_view(), name="club_application_list"),
    path('club/<int:club_id>/accept_application/<int:application_id>', views.AcceptApplicationView.as_view(), name='accept_application'),
    path('club/<int:club_id>/reject_application/<int:application_id>', views.RejectApplicationView.as_view(), name='reject_application'),   
    path('club/<int:club_id>/user/<int:user_id>', views.ShowUserView.as_view(), name='show_user'),
    path('club/<int:club_id>/promote_member/<int:user_id>', views.PromoteMemberView.as_view(), name='promote_member'),
    path('club/<int:club_id>/demote_officer/<int:user_id>', views.DemoteOfficerView.as_view(), name='demote_officer'),
    path('club/<int:club_id>/delete_member/<int:user_id>', views.DeleteMemberView.as_view(), name='delete_member'),
    path('club/<int:club_id>/transfer_ownership/<int:user_id>', views.TransferOwnershipView.as_view(), name="transfer_ownership"),   
    path('leave_club/<int:club_id>', views.LeaveClubView.as_view(), name='leave_club'),
    path('club/<int:club_id>/delete_club', views.DeleteClubView.as_view(), name="delete_club"),
    path('club/<int:club_id>/create_match', views.CreateMatchView.as_view(), name="create_match"),
    path('my_matches/', views.UserMatchesView.as_view(), name='user_matches'),
    path('club/<int:club_id>/update_match/<int:match_id>', views.UpdateMatchOutcomeView.as_view(), name="update_match"),
    path('club/<int:club_id>/forfeit_match/<int:match_id>', views.ForfeitMatchView.as_view(), name='forfeit_match'),
    path('club/<int:club_id>/cancel_match/<int:match_id>', views.CancelMatchView.as_view(), name="cancel_match"),

]

clubs/models/user_membership_models.py
"""The models that represent the users and their membership in a club."""

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from libgravatar import Gravatar
from clubs.models.helpers import UserManager

class User(AbstractUser):
    """User model used for authentication and is used to keep track applications/memberships."""
    username = models.CharField(max_length=30, unique=True, validators=[
        RegexValidator(
            regex=r'^\w{3,}$',
            message='Username must consist of at least three alphanumericals'
        )
    ])
    first_name = models.CharField(max_length=50, blank=False)
    last_name = models.CharField(max_length=50, blank=False)
    email = models.EmailField(unique=True, blank=False)
    bio = models.CharField(max_length=520, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    # Replaces default user manager with a costum one.
    objects = UserManager()

    # Status options for  the chess experience level
    BEGINNER = "Beginner"
    INTERMEDIATE = "Intermediate"
    ADVANCED = "Advanced"

    EXPERIENCE_LEVELS = [
        (BEGINNER, "Beginner"),
        (INTERMEDIATE, "Intermediate"),
        (ADVANCED, "Advanced"),
    ]

    experience_level = models.CharField(
        blank=False,
        max_length=12,
        choices=EXPERIENCE_LEVELS,
        default=BEGINNER,
    )

    def gravatar(self, size=120):
        """Return a URL to the user's gravatar which is derived from the email."""
        gravatar_object = Gravatar(self.email)
        gravatar_url = gravatar_object.get_image(size=size, default='mp')
        return gravatar_url

    def mini_gravatar(self):
        """Return a URL to the user's mini gravatar which is derived from the email."""
        return self.gravatar(size=50)

    def full_name(self):
        """Returns the user's full name."""
        return f'{self.first_name} {self.last_name}'

    def is_member(self):
        """Returns whether the user is a member in at least one club."""
        return len(Membership.objects.filter(user=self, role=Membership.MEMBER)) != 0

    def is_owner(self):
        """Returns whether the user is an owner in at least one club."""
        return len(Membership.objects.filter(user=self, role=Membership.OWNER)) != 0

    def is_officer(self):
        """Returns whether the user is an officer in at least one club."""
        return len(Membership.objects.filter(user=self, role=Membership.OFFICER)) != 0

    def is_member_of(self, club):
        """Returns whether the user is a member in a given club."""
        return len(Membership.objects.filter(user=self, role=Membership.MEMBER, club=club)) != 0

    def is_owner_of(self, club):
        """Returns whether a user is the owner of a given club."""
        return len(Membership.objects.filter(user=self, role=Membership.OWNER, club=club)) != 0

    def is_officer_of(self, club):
        """Returns whether a user is an officer of a given club."""
        return len(Membership.objects.filter(user=self, role=Membership.OFFICER, club=club)) != 0

    def clubs(self):
        """Returns a list of clubs that the user currently has a membership in."""
        membership = Membership.objects.filter(user=self)
        return Club.objects.filter(membership__in=membership)

    class Meta:
        """Model options, to provide ordering for the user model."""
        ordering = ['first_name', 'last_name']


class Club(models.Model):
    """Club model used for creating clubs."""
    name = models.CharField(max_length=30, unique=True, blank=False)
    location = models.CharField(max_length=180, unique=False, blank=False)
    description = models.CharField(max_length=520, blank=False)

    def __str__(self):
        """Returns the name of the club for the admin interface"""
        return self.name 

    def get_owner(self):
        """Returns the user of the club."""
        return Membership.objects.get(club=self,role=Membership.OWNER).user

    def get_member_count(self):
        """Returns how many members there are in the club."""
        return len(Membership.objects.filter(club=self))

class Membership(models.Model):
    """Membership model used for roles within a club."""
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        blank=False,
        null=False
    )

    club = models.ForeignKey(
        Club,
        on_delete=models.CASCADE,
        blank=False,
        null=False
    )

    # Role options for the different types of memberships
    MEMBER = "Member"
    OFFICER = "Officer"
    OWNER = "Owner"

    ROLE = [
        (MEMBER, "Member"),
        (OFFICER, "Officer"),
        (OWNER, "Owner"),
    ]

    role = models.CharField(max_length=8, choices=ROLE, default=MEMBER, blank=False)

    class Meta:
        """Model options, states that a user is allowed at maximum 
        1 membership per club."""
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'club'],
                name='one_membership_per_club'
            )
        ]

clubs/forms/club_forms.py
"""Form to create a new club."""

from django import forms
from clubs.models import Club

class CreateClubForm(forms.ModelForm):
    """Form enabling users to create a new club."""
   
    class Meta:
        """Form options."""
        model = Club
        fields = ['name', 'location', 'description']
        widgets = { 'description': forms.Textarea()}

    def get_club(self):
        """Returns newly created club if possible."""
        club = None
        if self.is_valid():
            club = Club.objects.create(
                name = self.cleaned_data.get('name'),
                location = self.cleaned_data.get('location'),
                description =self.cleaned_data.get('description')
            )
        return club    

clubs/views/account_views.py
"""Views that deal with the user account."""

from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import check_password
from django.shortcuts import redirect, render
from clubs.forms import UserForm, PasswordForm
from django.contrib import messages
from django.contrib.auth import login
from django.utils.decorators import method_decorator
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import PasswordResetForm
from clubs.views import login_prohibited
from django.views.generic.base import View
from clubs.models import User, Club
from django.contrib.auth.mixins import LoginRequiredMixin

"""View of the change profile details page."""
@login_required
def profile(request):
    current_user = request.user
    if request.method == 'POST':
        form = UserForm(instance=current_user, data=request.POST)
        if form.is_valid():
            messages.add_message(request, messages.SUCCESS, "Profile updated!")
            form.save()
            return redirect('dashboard')
    else:
        form = UserForm(instance=current_user)
    return render(request, 'account_templates/profile.html', {'form': form})


"""View of the change password page."""
@login_required
def password(request):
    current_user = request.user
    valid_current_password = True
    if request.method == 'POST':
        form = PasswordForm(data=request.POST)
        if form.is_valid():
            password = form.cleaned_data.get('password')
            if check_password(password, current_user.password):
                new_password = form.cleaned_data.get('new_password')
                current_user.set_password(new_password)
                current_user.save()
                login(request, current_user)
                messages.add_message(request, messages.SUCCESS, "Password updated!")
                return redirect('dashboard')
            else:
                valid_current_password = False
        if(not valid_current_password):
            form.add_error('password', 'Incorrect current password!')  
    else:
        form = PasswordForm()     
    return render(request, 'account_templates/password.html', {'form': form})


class PasswordResetView(auth_views.PasswordResetView):
    """View that handles password reset."""
    form_class = PasswordResetForm
    template_name = 'account_templates/password_reset.html'

    @method_decorator(login_prohibited)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)


class PasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    """View that handles password reset confirmation."""

    template_name = 'account_templates/password_reset_confirm.html'

    @method_decorator(login_prohibited)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class PasswordResetCompleteView(auth_views.PasswordResetCompleteView):
    """View for password reset completion."""

    template_name = 'account_templates/password_reset_complete.html'

    @method_decorator(login_prohibited)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class PasswordResetDoneView(auth_views.PasswordResetDoneView):
    """View for password reset that is done."""

    template_name = 'account_templates/password_reset_done.html'

    @method_decorator(login_prohibited)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class CloseAccountView(View):
    """View that handles account closure."""

    http_method_names = ['get', 'post']

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_owner():
            messages.add_message(request, messages.INFO, 'Cannot close account if you are an owner of one or more clubs. Transfer ownership or delete your clubs before closing your account')
            return redirect('dashboard')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        """Display close account template."""
        return render(request, 'account_templates/close_account.html', {'user': request.user.username})

    def post(self, request, *args, **kwargs):
        """Handle account closure attempt."""
        user = User.objects.get(username=request.user.username)
        user.delete()
        return redirect('home')

clubs/views/application_views.py
"""Views that deal with user's applications."""

from clubs.models import Application, Club
from clubs.forms import ApplicationForm
from django.views.generic import ListView
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist


class NewApplicationView(LoginRequiredMixin, View):
    """Create new application view class."""

    http_method_names = ['get', 'post']

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        """Get application form."""
        try:
            club_name = (Club.objects.get(id=kwargs['club_id'])).name
            self.form = ApplicationForm(initial={'club': club_name})
        except:
            self.form = ApplicationForm()
        return self.render()

    def post(self, request, *args, **kwargs):
        """Handle new application attempt."""
        self.form = ApplicationForm(request.POST)
        user = request.user
        for application in Application.objects.filter(user=user):
            if (application.club.name == request.POST.get('club')) and (
                    application.is_pending() or application.is_accepted()):
                messages.add_message(request, messages.ERROR, 'Application for this club has already been submitted')
                self.form = ApplicationForm()
                return self.render()
        if self.form.is_valid():
            self.form.save(user)
            messages.add_message(request, messages.SUCCESS, 'Application has been submitted')
            return redirect('applications')
        else:
            messages.add_message(request, messages.ERROR, 'Application has invalid format')
        return self.render()

    def render(self):
        return render(self.request, 'application_templates/new_application.html', {'form': self.form})


class ApplicationListView(LoginRequiredMixin, ListView):
    """View that displays user's list of applications."""
    model = Application
    template_name = "application_templates/application_list.html"
    context_object_name = 'applications'

    def get_queryset(self):
        """Return the logged in user's applications."""
        return Application.objects.filter(user=self.request.user)


class CancelApplicationView(LoginRequiredMixin, View):
    """Cancel application view class."""

    http_method_names = ['get', 'post']

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        """Cancel application."""
        return self.cancel_application(*args, **kwargs)

    def post(self, request, *args, **kwargs):
        """Cancel application."""
        return self.cancel_application(*args, **kwargs)

    def cancel_application(self, *args, **kwargs):
        try:
            application = Application.objects.get(id=kwargs['application_id'], user=self.request.user)
            if (application.is_pending()):
                application.delete()
                return redirect('applications')
            else:
                messages.add_message(self.request, messages.INFO,
                                     'Cannot cancel application that has already been processed.')
        except ObjectDoesNotExist:
            messages.add_message(self.request, messages.INFO,
                                 'The application you are trying to cancel does not exist.')
        applications_list = Application.objects.filter(user=self.request.user)
        return render(self.request, 'application_templates/application_list.html', {'applications': applications_list})

clubs/templates/account_templates/close_account.html
{% extends 'base_content.html' %}
{% block content %}
    <h2>Close account</h2>
    <p>Hi <b>{{ user }}</b>,</p>
    <p>we will be sad to see you go!</p>
    <hr style="width:50%;text-align:left;margin-left:0">
    <p> Make sure that you are signed in to the correct account.
        <br> You are signed in as <b>{{ user }}</b>. <br> If this is
        incorrect, logout and then log in with the correct account.</p>
    <hr style="width:50%;text-align:left;margin-left:0">
    <form action="{% url 'close_account' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        {% include 'partials/bootstrap_form.html' with form=form %}
        <input type="submit" onclick="return confirm('Are you sure you want to permanently close your account?')"
               value="Permanently close my account" class="btn btn-primary">
    </form>
{% endblock %}

clubs/templates/account_templates/dashboard.html
{% extends 'base.html' %}
{% block body %}
    {% include 'partials/navbar.html' %}
    <div class="container my-3">
    <div class="row">
    <div class="col-sm-12 col-md-10 offset-md-1">
    {% include 'partials/messages.html' %}
    <div class="container">
        <div class="row">
            <div class="col-12 ">
                <input type="search" id="search-input" class="form-control m-2 mb-3" placeholder="Find a club"/>
                <p class="text-danger lead" id="message" hidden>There are no clubs with that name!</p>
                <a href="{% url 'create_club' %}" class="btn btn-primary" style="float: right;"><i
                        class="fas fa-plus me-2"></i>Create club</a>
                <h2 id="my-clubs-label">My Clubs</h2>
                <div class="club-grid" id="my-clubs-grid">
                    {% if my_clubs %}
                        {% for club in my_clubs %}
                            {% include 'partials/club_list.html' with club=club member_of=True %}
                        {% endfor %}
                    {% else %}
                        <p class="text-info lead info-message">You are not in any clubs yet!</p>
                    {% endif %}
                </div>
                <hr id="divider"/>
                <h2 id="other-clubs-label">Other Clubs</h2>
                <div class="club-grid" id="other-clubs-grid">
                    {% if clubs %}
                        {% for club in clubs %}
                            {% include 'partials/club_list.html' with club=club member_of=False %}
                        {% endfor %}
                    {% else %}
                        <p class="text-info lead info-message">There are no other clubs!</p>
                    {% endif %}
                </div>
                <table class="table table-hover">
                </table>
            </div>
        </div>
    </div>
    <script>
        const searchInput = document.getElementById('search-input');
        const myClubsLabel = document.getElementById('my-clubs-label');
        const otherClubsLabel = document.getElementById('other-clubs-label');
        const divider = document.getElementById('divider');
        const message = document.getElementById('message');
        var allCards = document.getElementsByClassName("card club-card");
        var infoMessages = document.querySelectorAll(".info-message");
        var foundInMyClubs = false;
        var foundInOtherClubs = false;
        if (allCards.length == 0) {
            searchInput.disabled = true;
        }

        // Action taken when search input changes.
        searchInput.addEventListener('input', (e) => {
            showAllCards();
            updateDisplay(e);
            const inputValue = searchInput.value.toLowerCase();
            for (card of allCards) {
                var cardData = card.getElementsByClassName("card-header");
                for (header of cardData) {
                    var id = header.id
                    var club_name = header.textContent.toLowerCase();
                    if (id == 'club-name' && !club_name.startsWith(inputValue)) {
                        card.hidden = true;
                    } else if (id == 'club-name' && club_name.startsWith(inputValue)) {
                        if (card.parentElement.id == "my-clubs-grid") {
                            foundInMyClubs = true;
                        } else if (card.parentElement.id == "other-clubs-grid") {
                            foundInOtherClubs = true;
                        }
                    }
                }
                ;
            }
            if (!foundInMyClubs && !foundInOtherClubs) {
                message.hidden = false;
                divider.hidden = true;
                infoMessages.forEach(infoMessage => infoMessage.hidden = true)
                otherClubsLabel.hidden = true;
                myClubsLabel.hidden = true;
            } else if (foundInMyClubs && !foundInOtherClubs) {
                divider.hidden = true;
                infoMessages.forEach(infoMessage => infoMessage.hidden = true)
                otherClubsLabel.hidden = true;
            } else if (!foundInMyClubs && foundInOtherClubs) {
                divider.hidden = true;
                infoMessages.forEach(infoMessage => infoMessage.hidden = true)
                myClubsLabel.hidden = true;
            } else {
                message.hidden = true;
            }
        });

        function updateDisplay(e) {
            foundInMyClubs = e.target.value == '';
            foundInOtherClubs = e.target.value == '';
            message.hidden = true;
            divider.hidden = false;
            myClubsLabel.hidden = false;
            otherClubsLabel.hidden = false;
            infoMessages.forEach(infoMessage => infoMessage.hidden = false)

        }

        function showAllCards() {
            for (card of allCards) {
                card.hidden = false;
            }
        }
    </script>
{% endblock %}
</div>
</div>
</div>

clubs/templates/account_templates/home.html
{% extends 'base.html' %}
{% block body %}
    <div id="cover-image">
        <div class="container vh-100">
            <div class="row h-100">
                <div class="col-12 my-auto">
                    <div class="card cover-card shadow-lg mx-auto   ">
                        <h1 class="cover-heading">Polecat Chess</h1>
                        <p class="cover-text">Join a chess club today!</p>
                        <p>
                            <a href="{% url 'sign_up' %}" class="btn btn-primary">Sign Up</a>
                        </p>
                        <p>
                            <a href="{% url 'log_in' %}" class="btn btn-primary">Log In</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

clubs/templates/account_templates/password.html
{% extends 'base_content.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2>Change password</h2>
                <form action="{% url 'password' %}" method="post">
                    {% csrf_token %}
                    {% include 'partials/bootstrap_form.html' with form=form %}
                    <input type="submit" value="Change password" class="btn btn-primary">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

clubs/templates/account_templates/password_reset.html
{% extends 'base_content.html' %}
{% block content %}
    <h2>Password reset</h2>
    <p>Enter your email address below, and we will send an email with the instructions to set a new one.</p>
    <form action="{% url 'password_reset' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        {% include 'partials/bootstrap_form.html' with form=form %}
        <input type="submit" value="Reset password" class="btn btn-primary">
    </form>
{% endblock %}

clubs/templates/account_templates/password_reset_complete.html
{% extends 'base_content.html' %}
{% block content %}
    {% csrf_token %}
    <h2>Password successfully reset</h2>
    <p>Your password has been successfully set.</p>
    <a class="btn btn-primary" href="{% url 'log_in' %}">Back to login</a>
{% endblock %}

clubs/templates/account_templates/password_reset_confirm.html
{% extends 'base_content.html' %}
{% block content %}
    {% if validlink %}
        <h2>Password reset</h2>
        <p>Enter your email address below, and we will send an email with the instructions to set a new one.</p>
        <form action="" method="post">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ next }}">
            {% include 'partials/bootstrap_form.html' with form=form %}
            <input type="submit" value="Reset password" class="btn btn-primary">
        </form>
    {% else %}
        <h2>Password reset unsuccessful</h2>
        <p>The password reset link was invalid/expired.</p>
    {% endif %}
{% endblock %}

clubs/templates/account_templates/password_reset_done.html
{% extends 'base_content.html' %}
{% block content %}
    <h2>Password reset</h2>
    <p>We have sent an email to the given address with a link to reset the password, make sure you check your spam
        folder as well.</p>
{% endblock %}

clubs/templates/account_templates/profile.html
{% extends 'base_content.html' %}
{% block content %}
    <h2>Edit profile</h2>
    <form action="{% url 'profile' %}" method="post">
        {% csrf_token %}
        {% include 'partials/bootstrap_form.html' with form=form %}
        <input type="submit" value="Update" class="btn btn-primary">
    </form>
    <hr>
    <a class="text-primary" href="{% url 'password' %}">Change password</a>
    <br>
    <a class="text-danger" href="{% url 'close_account' %}">Close account</a>
{% endblock %}